version: "2"

services:

    server:
        build:
            context: .
            dockerfile: build/Dockerfile.dev
        command:
            - go
            - run
            - cmd/server/server.go
            - --psql-host=postgresql
            - --psql-db=default
            - --psql-user=admin
            - --psql-pass=secret
            - --publish-host=0.0.0.0
            - --http-port=80
            - --ui-enabled=true
            - --log-file=/dev/stdout
            - --log-level=debug
        depends_on:
            - postgresql
        ports:
            - "80:80"
        volumes:
            - ./cmd:/go/src/github.com/supergiant/supergiant/cmd
            - ./pkg:/go/src/github.com/supergiant/supergiant/pkg
            - ./test:/go/src/github.com/supergiant/supergiant/test
            - ./vendor:/go/src/github.com/supergiant/supergiant/vendor
            - ./data:/data

    postgresql:
        image: mediamoose/postgresql:9.4-2
        ports:
            - "5432:5432"
        volumes:
            - postgresql:/var/lib/postgresql
        environment:
            POSTGRESQL_DB_NAME: default
            POSTGRESQL_DB_USER: admin
            POSTGRESQL_DB_PASS: secret

volumes:
    postgresql: {}
